export const DRINKING_QUESTIONS = [
  "Uống 1 ly nếu bạn đang độc thân.",
  "Chỉ định một người uống cùng bạn.",
  "Uống 2 ly nếu bạn từng hôn ai đó trong phòng này.",
  "Tất cả con trai uống 1 ly.",
  "Người mặc áo màu đen uống 1 ly.",
  "Uống 1 ly nếu bạn đã từng đi muộn trong tuần này.",
  "Chỉ định 2 người, mỗi người uống 1 ly.",
  "Uống 1 ly, hoặc kể một bí mật.",
  "Tất cả con gái uống 1 ly.",
  "Người trẻ tuổi nhất uống 1 ly.",
  "Uống 1 ly nếu bạn chưa có người yêu.",
  "Người ngồi bên phải bạn uống 1 ly.",
  "Bạn và người đối diện cùng uống 1 ly.",
  "Những ai đeo kính uống 1 ly.",
  "Ai đang cầm điện thoại trên tay, uống 1 ly.",
  "Uống 1 ly nếu bạn có hình xăm.",
  "Ai tóc ngắn uống 1 ly.",
  "Chỉ định 1 người hát 1 bài, hoặc người đó phải uống.",
  "Uống 2 ly nếu bạn đã từng 'thả thính' một ai đó trong phòng này.",
  "Tất cả mọi người cùng nâng ly!",
  "Người ngồi bên trái bạn uống 1 ly.",
  "Uống 1 ly nếu bạn từng đi du lịch một mình.",
  "Hãy kể tên 3 loại bia trong 5s. Nếu không được, uống 1 ly.",
  "Người có followers Instagram nhiều nhất uống 1 ly.",
  "Mọi người chỉ vào người uống kém nhất. Người đó uống 1 ly.",
  "Uống 1 ly nếu bạn đang để tóc nhuộm.",
  "Chỉ định một cặp đôi uống rượu giao bôi.",
  "Những ai chưa từng thất tình uống 1 ly.",
  "Uống 1 ly nếu bạn từng 'cắm sừng' hoặc bị 'cắm sừng'.",
  "Tất cả những ai sinh vào mùa hè uống 1 ly.",
  "Uống 1 ly nếu bạn từng nói dối cha mẹ để đi chơi.",
  "Chọn một người, đấm oẳn tù tì. Người thua uống.",
  "Ai đang có tiệt mục dở khóc dở cười nhất gần đây uống 1 ly.",
  "Uống 1 ly nếu bạn từng ngủ gật trong lớp/công ty.",
  "Những ai có tên bắt đầu bằng chữ 'T', 'H', 'M' uống 1 ly.",
  "Hãy khen người bên cạnh 1 câu, nếu người đó không cười, bạn uống.",
  "Uống 1 ly nếu bạn từng xem phim kinh dị một mình.",
  "Tất cả những ai có anh/chị/em ruột uống 1 ly.",
  "Uống 1 ly nếu bạn từng gửi nhầm tin nhắn cho người khác.",
  "Chỉ định 1 người, người đó uống hoặc tự mình uống 2 ly.",
  "Những ai biết chơi guitar uống 1 ly.",
  "Ai có mang theo tiền mặt nhiều nhất, người đó an toàn, những người còn lại uống.",
  "Uống 1 ly nếu bạn đã từng thi rớt môn.",
  "Người lớn tuổi nhất uống 1 ly.",
  "Mọi người cùng đếm 1, 2, 3... ai nói số trùng nhau thì cả hai cùng uống.",
  "Uống 1 ly nếu bạn từng khóc vì một bộ phim.",
  "Tất cả những ai đi giày sneakers uống 1 ly.",
  "Uống 1 ly nếu bạn từng yêu đơn phương trên 3 năm.",
  "Hãy kể một câu chuyện cười, nếu không ai cười, bạn uống.",
  "Cả bàn cùng hô to '1, 2, 3.. dzô!' và uống 1 ly.",
];

export const DRINKING_CHALLENGES = [
  "Uống 1 ly mà không được dùng tay.",
  "Uống liên tục 3 ngụm.",
  "Đứng lên múa quạt và uống 1 ly.",
  "Mời người bên phải uống 1 ly.",
  "Uống chéo tay với người đối diện.",
  "Nhắm mắt lại và uống 1 ly do người khác tự ý pha.",
  "Uống 1 nửa ly của bạn.",
  "Hát 1 bài hát, trong lúc hát phải uống hết 1 ly.",
  "Đứng bằng 1 chân và uống ly bia.",
  "Vừa nhảy lò cò vừa uống.",
  "Nhờ người bên trái cho bạn uống.",
  "Uống 1 ly 100% bằng ống hút.",
  "Cụng ly cụng trán với người bên cạnh rồi uống.",
  "Đọc 1 bài thơ lục bát tự chế trước khi uống.",
  "Nói 'Em say rồi' bằng giọng ngọt ngào nhất, sau đó uống.",
  "Quay 3 vòng tại chỗ rồi uống 1 ly.",
  "Uống 1 ly và không được làm mất nụ cười trên môi.",
  "Nhờ một bạn khác phái đút cho uống.",
  "Tỏ tình với cái ly rồi uống nó.",
  "Uống 1 ly mà không được nuốt trôi trong 5s đầu.",
  "Uống 1 ly và làm mặt xấu nhất có thể khi uống xong.",
  "Dùng hai ngón tay cái kẹp ly và uống.",
  "Uống 1 ly, nếu để rớt 1 giọt, uống thêm ly nữa.",
  "Vừa hít đất 5 cái vừa uống (người khác đút).",
  "Uống 1 ly với đá lạnh buốt.",
  "Gọi điện cho đồng nghiệp nói 'Mai tao nghỉ' sau đó uống 1 ly.",
  "Uống 1 ly và sau đó gáy như gà 3 tiếng.",
  "Cho người khác thêm 1 gia vị bất kỳ (chanh/muối) vào ly bạn và uống.",
  "Vừa hát rap vừa uống.",
  "Đeo mắt kính ngược và uống 1 ly.",
  "Uống 1 ly và sau đó khen ly rượu 'Ngon tuyệt cú mèo'.",
  "Đứng lên ghế, hô to 'Tôi tửu lượng vô địch' rồi uống.",
  "Uống 1 ly và nói 1 câu châm ngôn sống ngớ ngẩn.",
  "Vừa uống vừa làm động tác nhướn mày.",
  "Uống 1 ly và không được chớp mắt trong lúc uống.",
  "Nhờ người đối diện bón rượu bằng thìa.",
  "Uống xong kêu meo meo 3 lần.",
  "Uống ly của bạn và ly của người bên cạnh.",
  "Ngậm nước trong 30s không nuốt, ai chọc cười để sặc phải uống ly khác.",
  "Vừa uống vừa khóc giả vờ (khóc có tiếng).",
  "Bịt mũi lại và uống cạn 1 ly.",
  "Uống 1 ly, nếu trong 10 phút đi toilet, quay lại uống thêm ly nữa.",
  "Nhờ người khác cầm đuôi tóc của bạn khi bạn uống.",
  "Thách đó tay đôi người bên phải, ai uống nhanh hơn người kia an toàn.",
  "Uống 1 ly trộn lẫn 2 loại nước trên bàn.",
  "Quỳ gối xin phép ly rượu trước khi uống.",
  "Uống 1 ly và sau đó diễn một đoạn kịch câm.",
  "Vừa uống vừa nắm tay người bên cạnh thật chặt.",
  "Uống 1 ly và miêu tả cảm giác bằng 3 từ không nghĩa.",
  "Uống xong phải nhảy vũ điệu Michael Jackson trong 10s.",
];
