export const TRUTH_QUESTIONS = [
  "Người yêu cũ nhắn tin 'Em dạo này ổn không?', bạn trả lời sao?",
  "Bí mật lãng nhách nhất mà bạn từng che giấu là gì?",
  "Ai là người bạn từng 'crush' trong nhóm này?",
  "Kể tên một tật xấu của bạn khi ở một mình.",
  "Bạn đã từng nói dối để trốn nợ chưa?",
  "Lần cuối cùng bạn khóc vì thất tình là bao giờ?",
  "Đánh giá nhan sắc của bản thân trên thang điểm 10?",
  "Bạn có bao giờ vào Facebook người yêu cũ mỗi ngày không?",
  "Kể về nụ hôn đầu của bạn, nó có tệ như trên phim không?",
  "Lời nói dối 'kinh điển' nhất bạn từng nói với ba mẹ là gì?",
  "Bạn có đang để ý ai trong căn phòng này không?",
  "Món đồ đắt tiền nhất bạn từng mua nhưng hối hận là gì?",
  "Nếu được chọn tin đồn về bản thân, bạn muốn người ta đồn gì?",
  "Ngày tồi tệ nhất bạn từng trải qua trông như thế nào?",
  "Bạn từng bị người khác 'cắm sừng' bao giờ chưa?",
  "Nếu kiếp sau phải cưới một người ở đây, bạn chọn ai?",
  "Việc điên rồ nhất bạn từng làm vì tình yêu là gì?",
  "Khai thật đi, bạn tắm mấy lần một tuần vào mùa đông?",
  "Người cuối cùng bạn nhắn tin trước khi đi ngủ hôm qua là ai?",
  "Câu thả thính xàm nhất mà bạn từng dùng và có thành công không?",
  "Bạn từng có suy nghĩ đen tối với người nào trong nhóm chưa?",
  "Nếu bị mắc kẹt trên đảo hoang, bạn tuyệt đối không muốn đi cùng ai trong đây?",
  "Gần đây nhất bạn 'bùng' kèo với lý do giả dối là khi nào?",
  "Bạn đã bao giờ khóc trong nhà vệ sinh công cộng chưa?",
  "Điều gì khiến bạn cảm thấy tự ti nhất về bản thân?",
  "Nếu có năng lực tàng hình trong 1 ngày, bạn sẽ làm gì đầu tiên?",
  "Đã bao giờ bạn giả vờ nghe điện thoại để tránh gặp người quen chưa?",
  "Bạn thích được theo đuổi hay là làm người chủ động đi theo đuổi?",
  "Cảm giác lúc biết mình bị cắm sừng như thế nào? (Nếu chưa thì báo lúc bị từ chối)",
  "Mối tình ngắn nhất của bạn kéo dài bao lâu?",
  "Đã bao giờ lập nick clone để đi stalk người bị ghét chưa?",
  "Ấn tượng đầu tiên của bạn về người ngồi đối diện là gì?",
  "Kể tên một bộ phim hoạt hình bạn vẫn xem đến tận bây giờ.",
  "Lần gần nhất bạn 'quê xệ' trước đám đông là khi nào?",
  "Bạn sợ con vật gì nhất trên đời?",
  "Có bao giờ nhặt được tiền mà không trả lại chưa?",
  "Thói quen kỳ quặc nhất trước khi đi ngủ của bạn là gì?",
  "Kỷ niệm đáng xấu hổ nhất thời đi học là gì?",
  "Người bạn muốn 'táng' nhất trong căn phòng này là ai?",
  "Bạn từng hôn nhầm người chưa?",
  "Sự thật nào về bạn mà ba mẹ bạn nghe xong sẽ sốc?",
  "Nếu phải chọn giữa 'Độc thân giàu nứt vách' và 'Có bồ nhưng nghèo rớt', bạn chọn?",
  "Bạn từng ăn vụng đồ của bạn cùng phòng/anh chị em chưa?",
  "Đã có ai tỏ tình mà bạn phải trốn biệt tăm không?",
  "Lời khen thảo mai nhất bạn từng thốt ra là gì?",
  "Bạn có hay check trộm điện thoại người yêu (hiện tại/cũ) không?",
  "Điều hối tiếc lớn nhất trong tình yêu của bạn là gì?",
  "Nếu có cỗ máy thời gian, bạn muốn xóa bỏ sự kiện bẽ mặt nào?",
  "Kể lại một giấc mơ 18+ mà bạn từng có (nói giảm nói tránh).",
  "Bạn tự chấm điểm sự quyến rũ của bản thân được mấy điểm?"
];

export const DARE_CHALLENGES = [
  "Gọi điện cho người yêu cũ (hoặc crush) và hát bài 'Chắc ai đó sẽ về'.",
  "Đăng lên story Facebook: 'Đang tìm người yêu gấp' trong vòng 1 tiếng.",
  "Múa quạt 30 giây cho cả hội xem.",
  "Nhắn tin cho mẹ: 'Con mới trúng số 10 tỷ' rồi chụp màn hình lại.",
  "Uống cạn ly nước của người ngồi bên trái.",
  "Chống đẩy 20 cái ngay lập tức.",
  "Quay sang người bên phải và tỏ tình bằng ánh mắt đắm đuối trong 30 giây.",
  "Để mọi người chọn một người trong danh bạ và bạn phải nhắn 'Em yêu anh/Anh yêu em'.",
  "Ngậm một ngụm nước và để mọi người chọc cười, bị phun là thua.",
  "Hát một bài hát thiếu nhi nhưng theo phong cách opera.",
  "Chạy ra cửa sổ và hét lớn: 'Tôi đẹp quá thể đáng!'",
  "Tạo dáng 'chanh sả' nhất để mọi người chụp hình dìm hàng.",
  "Đi bằng hai đầu gối quanh phòng một vòng.",
  "Biểu diễn một điệu nhảy TikTok thịnh hành nhất hiện nay.",
  "Ôm một người bạn khác giới gần bạn nhất trong 5 giây.",
  "Đứng lên và catwalk như siêu mẫu đi quanh phòng.",
  "Hôn lên trán hoặc má người ngồi bên trái bạn.",
  "Cho mọi người xem bức ảnh gần nhất trong thư viện điện thoại.",
  "Nắm tay người bên cạnh liên tục cho đến lượt tiếp theo.",
  "Đội một đồ vật bất kỳ do mọi người chọn lên đầu trong 2 lượt tới.",
  "Đăng một tấm ảnh dìm hàng nhất của bạn lên story 10 phút.",
  "Nhắn tin cho sếp/giáo viên: 'Em nhớ sếp/thầy cô!' (hoặc một tin nhắn lầy lội).",
  "Bắt chước tiếng kêu và điệu bộ của một con khỉ trong 1 phút.",
  "Ăn một muỗng cà phê tương ớt hoặc mù tạt (nếu có).",
  "Cho phép người đối diện vẽ một nét lên mặt bạn bằng son/bút.",
  "Kể một câu chuyện cười nhạt nhẽo nhất có thể.",
  "Đứng ôm tường và nói chuyện với nó trong vòng 30 giây như người yêu.",
  "Tháo một chiếc tất và đeo nó vào tay cho đến hết trò chơi.",
  "Gọi điện thoại cho một tiệm pizza để hỏi họ có bán bún bò không.",
  "Đổi áo cho người cùng giới tay trong tay 1 phút.",
  "Hát bài 'Happy Birthday' bằng giọng trầm nhất có thể.",
  "Nhắm mắt lại và để mọi người cho bạn nếm một thứ đồ ăn/uống bí mật.",
  "Làm mặt xấu nhất có thể và giữ yên trong 15 giây để mọi người chụp hình.",
  "Nói xin chào với mọi người bằng 5 ngôn ngữ khác nhau.",
  "Mượn điện thoại người bên cạnh và like dạo 5 post đầu tiên trên Facebook.",
  "Đọc to 3 tin nhắn gần nhất trong hộp thư thoại/Messenger của bạn.",
  "Uống hỗn hợp nước (trà+muối+tiêu...) do mọi người chế (mức độ an toàn nhé).",
  "Phải nói 'Meo' sau mỗi câu nói cho tới lượt tiếp theo.",
  "Quay 3 vòng rồi cố gắng đi thẳng trên một đường kẻ tưởng tượng.",
  "Để một người làm tóc cho bạn và phải giữ kiểu đó đến hết game.",
  "Chơi oẳn tù tì với bức tường, nếu thua phải chống đẩy 5 cái.",
  "Ngồi xổm kiểu ếch và nhảy một vòng quanh phòng.",
  "Cầm một cái chổi và biểu diễn đánh đàn guitar cháy nhất có thể.",
  "Đăng lên Facebook: 'Hôm nay tôi chưa tắm, có ai yêu tui không?'",
  "Nhắm mắt đoán tên 3 vật dụng mọi người đưa cho bạn sờ vào.",
  "Để tay người bên trái lên đầu bạn xoa xoa và bạn phải cười giả trân.",
  "Nhắn tin 'Vay 5 triệu mai trả' cho người đầu tiên vừa online trong danh bạ.",
  "Mở Google Translate cho nó phát âm một câu thả thính cực sến.",
  "Bị cù léc trong vòng 15 giây mà không được cười lớn.",
  "Hít đất 10 cái và mỗi cái phải hô to: 'Tôi là kẻ yếu đuối!'."
];
